[build] new version of makemore

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,25 @@ function argument {
 	echo ${1} | awk 'BEGIN { FS = "="} {print $2}'
 }
 
+function help {
+	echo "${0} [options]"
+	printf "Configuration:\n"
+	printf "\t--help\t\t\tdisplay this help and exit\n"
+	printf "Installation directories:\n"
+	printf "\t--prefix=PREFIX\t\tinstall architecture-independent files in PREFIX [/usr/local]\n"
+	printf "\t--bindir=DIR\t\tuser executables [PREFIX/bin]\n"
+	printf "\t--sbindir=DIR\t\tsystem admin executables [PREFIX/sbin]\n"
+	printf "\t--sysconfdir=DIR\tread-only single-machine data [PREFIX/etc]\n"
+	printf "\t--libdir=DIR\t\tobject code libraries [PREFIX/lib]\n"
+	printf "\t--includedir=DIR\tC header files [PREFIX/include]\n"
+	printf "\t--datadir=DIR\t\tread-only architecture-independent data [PREFIX/share]\n"
+	printf "System types:\n"
+	printf "\t--build=BUILD\t\tconfigure for building on BUILD [guessed]\n"
+	printf "\t--host=HOST\t\tcross-compile to build programs to run on HOST [BUILD]\n"
+	printf "\t--sysroot=DIR\t\tcross-compiler root directory [none]\n"
+	exit
+}
+
 while [ "${1}" != "" ]; do
 	case ${1} in
 		--prefix*)
@@ -39,21 +58,11 @@ while [ "${1}" != "" ]; do
 			sysroot=$(argument ${1})
 			;;
 		--help*)
-			echo "${0} [options]"
-			printf "Configuration:\n"
-			printf "\t--help\tdisplay this help and exit\n"
-			printf "Installation directories:\n"
-			printf "\t--prefix=PREFIX\tinstall architecture-independent files in PREFIX [/usr/local]\n"
-			printf "\t--bindir=DIR\tuser executables [PREFIX/bin]\n"
-			printf "\t--sbindir=DIR\system admin executables [PREFIX/sbin]\n"
-			printf "\t--sysconfdir=DIR\tread-only single-machine data [PREFIX/etc]\n"
-			printf "\t--libdir=DIR\tobject code libraries [PREFIX/lib]\n"
-			printf "\t--includedir=DIR\tC header files [PREFIX/include]\n"
-			printf "\t--datadir=DIR\tread-only architecture-independent data [PREFIX/share]\n"
-			printf "System types:\n"
-			printf "\t--build=BUILD\tconfigure for building on BUILD [guessed]\n"
-			printf "\t--host=HOST\tcross-compile to build programs to run on HOST [BUILD]\n"
-			printf "\t--sysroot=DIR\tcross-compiler root directory [none]\n"
+			help
+			;;
+		*)
+			printf "\x1B[31m\n\tbad argument: ${1}\n\n\x1B[0m"
+			help
 	esac
 	shift
 done
@@ -74,12 +83,25 @@ if [ -z ${sysconfdir} ]; then
 	sysconfdir=${prefix}/etc
 fi
 
+echo "#Makemore 1.0" > $out
 echo "prefix=\""$prefix"\"" >> $out
 echo "bindir=\""$bindir"\"" >> $out
 echo "sbindir=\""$sbindir"\"" >> $out
 echo "includedir=\""$includedir"\"" >> $out
 echo "libdir=\""$libdir"\"" >> $out
 echo "sysconfdir=\""$sysconfdir"\"" >> $out
+if [ $sysroot ]; then
+	echo "sysroot=\""$sysroot"\"" >> $out
+fi
 if [ $CROSS_COMPILER ]; then
 	echo "CROSS_COMPILER="$CROSS_COMPILER >> $out
+fi
+
+if [ ! -e config -a -e default.config ]; then
+	cp default.config config
+fi
+make check
+if [ $? != 0 ]; then
+	echo "binary dependences failed"
+	exit -1
 fi
